### ISSUE TITLE
tweaking of oauth scopes required for oneNote notebooks hosted outside of Sharepoint

### ISSUE THREAD

**Issue by ladworkin** [hirenj/knoter#1]
https://github.com/CopenhagenCenterForGlycomics/knoter/blob/e8c9040d2ca6b72309a6cd2d1b90033d6272eab9/R/oauth.R#L118

Suggested Oauth scopes for suggested setup:

- Notes.Create
- Notes.ReadWrite
- Sites.Read.All

I don't know how difficult it would be to implement this off the top of my head, but I think it would be great for quality of life 👍

**Comment by hirenj** [comment]
Fixed in Commit  edba7f8 , rolled into version 0.5.9, 35ad45767895e5a7f345f6ffbf97e0a80b64a025
