### ISSUE TITLE
consider implementation of per analysis folder for generated excel sheets

### ISSUE THREAD

**Issue by ladworkin** [hirenj/knoter#2]
IE, if the filename of an analysis is "foo.Rmd", an excel sheet called "bar.xlsx" from this analysis will be written to "foo/bar.xlsx" instead of "knoter_data/bar.xlsx". I think this is a good idea when keeping track of multiple analyses within a single repo.

https://github.com/CopenhagenCenterForGlycomics/knoter/blob/35ad45767895e5a7f345f6ffbf97e0a80b64a025/R/knit.R#L377

**Comment by hirenj** [comment]
knitr::opts_chunk$set(fig.path="figures/somedir/", data.path="data/whatever/")
