### ISSUE TITLE
consider implementation of per analysis folder for generated figures

### ISSUE THREAD

**Issue by ladworkin** [hirenj/knoter#3]
Same justification. Of course folder names hosting figures and excel sheets should have names corresponding to analysis.
Example: In addition to cache_foo, there would now be a knoter_data_foo, and a figure_foo. I've no preference as to whether analysis name is suffix or prefix, but maybe you do.

https://github.com/CopenhagenCenterForGlycomics/knoter/blob/35ad45767895e5a7f345f6ffbf97e0a80b64a025/R/knit.R#L408

**Comment by hirenj** [comment]
knitr::opts_chunk$set(fig.path="figures/somedir/", data.path="data/whatever/")
